# NASA Battery Dataset Understanding

## Objective

The objective of this notebook is to understand the NASA Battery Dataset before preprocessing.

### Tasks
- Load one sample battery CSV
- Inspect the dataset
- Check the structure
- Understand the features
- Generate statistical summary

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
import pandas as pd

In [3]:
from src.core.data_loader import load_csv

In [4]:
df = load_csv("05122.csv")

In [5]:
df.head()

,Voltage_measured,Current_measured,Temperature_measured,Current_load,Voltage_load,Time
0,4.191492,-0.004902,24.330034,-0.0006,0.000,0.000
1,4.190749,-0.001478,24.325993,-0.0006,4.206,16.781
2,3.974871,-2.012528,24.389085,-1.9982,3.062,35.703
3,3.951717,-2.013979,24.544752,-1.9982,3.030,53.781
4,3.934352,-2.011144,24.731385,-1.9982,3.011,71.922

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Voltage_measured      197 non-null    float64
 1   Current_measured      197 non-null    float64
 2   Temperature_measured  197 non-null    float64
 3   Current_load          197 non-null    float64
 4   Voltage_load          197 non-null    float64
 5   Time                  197 non-null    float64
dtypes: float64(6)
memory usage: 9.4 KB

In [7]:
df.describe()

,Voltage_measured,Current_measured,Temperature_measured,Current_load,Voltage_load,Time
count,197.000000,197.000000,197.000000,197.000000,197.000000,197.000000
mean,3.529829,-1.818702,32.572328,-1.805570,2.404944,1812.087497
std,0.236558,0.595058,3.495804,0.591217,0.796974,1069.272600
min,2.612467,-2.018015,24.325993,-1.998400,0.000000,0.000000
25%,3.418746,-2.013447,30.422589,-1.998200,2.498000,891.812000
50%,3.529903,-2.012427,32.865786,-1.998200,2.610000,1796.328000
75%,3.685214,-2.011144,35.095568,-1.998200,2.765000,2724.203000
max,4.191492,0.000729,38.982181,-0.000400,4.206000,3690.234000

## Key Learnings

- Successfully loaded NASA battery data.
- Understood dataset structure.
- Verified data quality.
- Identified important battery parameters.
- Prepared the dataset for profiling.